# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: My devblog
repo_url: https://github.com/DrBenton/devblog
site_description: "Olivier Philippon's devblog."

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Rougemine
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/DrBenton
      name: Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/olivierphilippon/
      name: LinkedIn

# Copyright
copyright: Copyright &copy; 2022 Olivier Philippon

theme:
  name: material
  palette:
    # @link https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono        
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - content.code.annotate
  icon:
    logo: octicons/log-16

extra_css:
    - stylesheets/extra.css
    
edit_uri: ""
  
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - pymdownx.magiclink
  - attr_list
  - admonition
  - meta
  - toc:
      title: On this page
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Syntax highlighting:
  # @link https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  # @link https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions
  - pymdownx.highlight:
      auto_title: true      
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - awesome-pages:
      strict: false
  - search
  - tags:
      tags_file: tags.md
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: "my_plugins.blog_toc:on_page_markdown"
